### ISSUE TITLE
How to define locales?

### ISSUE THREAD

**Issue by hmaesta** [lloydjatkinson/vue-numeral-filter#1]
Numeral.js allow use of locales. 

```js
numeral.locale('fr');
```

How to determine what locale should be used in vue-numeral-filter?

**Comment by lloydjatkinson** [comment]
Hi,

This feature has been implemented in the latest version, please update.

```
Vue.use(vueNumeralFilterInstaller, { locale: 'fr' });
```

Thanks! :smile:

**Comment by michalhudecek** [comment]
Hi, I cannot figure out how to change it on the fly. What's the proper way to do it?
