### ISSUE TITLE
Defaults to 'en-gb' if no locale is specified

### ISSUE THREAD

**Issue by D144** [lloydjatkinson/vue-numeral-filter#2]
After updating to version 1.1.1 of the plugin, currency is displayed in British Pounds instead of U.S. dollars and there is no way to set locale to something like 'en-us'

**Comment by lloydjatkinson** [comment]
Hi,

`Vue.use(vueNumeralFilterInstaller, { locale: 'en' });`

With numeral.js, `en` is the default locale and will default to US dollars.

**Comment by lloydjatkinson** [comment]
Any luck?

**Comment by D144** [comment]
It’s weird. I added locale: ‘en’ to the configuration and on my staging server I get  $  but in production I get  £,  which is even more confusing since this is a client side library   
  

  
  

  
>
