### ISSUE TITLE
【有警告】缺少index.d.ts文件，

### ISSUE THREAD

**Issue by 120011676** [lloydjatkinson/vue-numeral-filter#20]
TS7016: Could not find a declaration file for module 'vue-numeral-filter'. '/Volumes/Say-0/git/jiaxipera-qms-web-v2/node_modules/vue-numeral-filter/dist/vue-numeral-filter.es.js' implicitly has an 'any' type.   Try `npm install @types/vue-numeral-filter` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-numeral-filter';`

![image](https://user-images.githubusercontent.com/1992933/148933817-578d7e77-4145-425a-857b-fa50e6a6005f.png)

**Comment by lloydjatkinson** [comment]
https://github.com/lloydjatkinson/vue-numeral-filter/issues/3
