### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by davidzhao** [lloydjatkinson/vue-numeral-filter#3]
I would like to use this library in my project, which uses typescript.

As TS becomes a more popular choice for Vue developers, is it possible to provide a .d.ts definitions file for this project?

Your help is much appreciated.

**Comment by davidzhao** [comment]
I've written a basic version of this here.

```
declare module 'vue-numeral-filter' {
  import Vue, { ComponentOptions, PluginObject } from 'vue'
  import { VueConstructor, Vue as _Vue, ExtendedVue } from 'vue/types/vue'

  interface LocaleOpts {
    locale: string;
  }

  export class Installer {
    install(vue: typeof _Vue, opts: LocaleOpts): void
  }

  export const vueNumeralFilterInstaller: PluginObject<LocaleOpts>
  export default vueNumeralFilterInstaller
}
```

**Comment by lloydjatkinson** [comment]
Right now I'm not planning on converting the library to TS. There's a couple of reasons for this but one being how painful it is to get typings being generated _and_ published correctly. I may revisit this at some point in the future.

That typing definition is hopefully suitable for most people, or perhaps simply use `// @ts-ignore` on the usage of it. Given that the library is imported and used once in `main.js/main.ts` I think that's fine to do. This library is only used via filters anyway, so there's no typing support in the handlebar interpolation anyway.
