### ISSUE TITLE
How to install this in nuxt.js?

### ISSUE THREAD

**Issue by bf** [lloydjatkinson/vue-numeral-filter#5]
I tried installing it as a nuxt.js module and as a plugin. When installed as a nuxt.js module in nuxt config, it does not work. When installed as nuxt.js plugin, it only works on the client-side (with `ssr: false` in nuxt config.

On top of this it then throws an error `[Vue warn]: Failed to resolve filter: bytes`.

Can you please point me into the right direction? Thank you.

**Comment by Aeka123** [comment]
Hey i got it working by simply following the Nuxt plugin docs.

/plugins/vue-numeral-filter.js
`import Vue from 'vue';
import vueNumeralFilterInstaller from 'vue-numeral-filter';

Vue.use(vueNumeralFilterInstaller);`

And in the config (nuxt.config.js) i simply added the path along with `ssr: false` which was the reason why it didn't work for me.
`  plugins: [{ src: '~/plugins/vue-numeral-filter.js', ssr: false }],`

And it's called like the docs state.
`561739482 | numeral('0,0')`

Hope this helps.

**Comment by lloydjatkinson** [comment]
https://nuxtjs.org/guide/plugins/
