### ISSUE TITLE
nan-fix

### ISSUE THREAD

**Issue by trasigor** [lloydjatkinson/vue-numeral-filter#6]
The is an issue on original Numeral-js which return NaN for too big or too small numbers.
I also found a fix https://github.com/dsagal/Numeral-js/tree/nan-fix
Can you please use the code from this fork and branch or some other fix since the original master branch wasn't update for about 2 years?

**Comment by lloydjatkinson** [comment]
Unfortunately this would be both a breaking change and change the underlying dependency to a random fork that appears to have little to no users.

- The fork doesn't have a NPM module - this is a no go as I am not willing to replace a dependency and replace it by effectively copy and pasted fixes.
 - Even if it did have a NPM module unless it has a significant user base it could be a potential security risk.

I don't feel comfortable swapping over to this fork for these reasons.

The best option really would be to somehow convince @adamwdraper to stop ignoring his library and accept the many PR's that have piled up. Unfortunately he seems unwilling to cooperate based on the numersous issues on its repo.
